export const regionMap: { [key: string]: string} = {
    "br1": "br",
    "br": "br",
    "eun1": "eune",
    "eune": "eune",
    "euw1": "euw",
    "euw": "euw",
    "jp1": "jp",
    "jp": "jp",
    "kr": "kr",
    "la1": "lan",
    "lan": "lan",
    "la2": "las",
    "las": "las",
    "na1": "na",
    "na": "na",
    "oce": "oce",
    "oc1": "oce",
    "tr1": "tr",
    "tr": "tr",
    "ru": "ru",
    "pbe": "pbe1",
    "pbe1": "pbe"
}